# Préparer l'environnement dbus/systemd
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP
exec-once = waypaper --restore

# Bar de status
exec-once = nm-applet --indicator
exec-once = waybar 

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Charge les plugins au démarrage 
# exec-once = hyprpm reload -n

# Pour lancer quickshell
#exec-once = quickshell --path .config/quickshell/DankMaterialShell/

# Pour lancer le dock
#exec-once = crystal-dock

# Pour utiliser thunar en mode admin
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Mise en veille
exec-once = hypridle

# Applications start
exec-once = discord

# Scripts
# exec-once = ~/.config/hypr/scripts/launch_hyprpanel_dynamic.sh
exec-once = /home/kovasko/.config/hypr/scripts/mount_network_drive.sh 
 
